steps:
  - id: 'format'
    name: 'mcr.microsoft.com/dotnet/sdk:6.0.102-focal'
    entrypoint: dotnet
    args: ['format', '--verify-no-changes', '-v', 'diagnostic', '--no-restore']

  - id: 'build'
    name: 'mcr.microsoft.com/dotnet/sdk:6.0.102-focal'
    entrypoint: 'dotnet'
    args: ['build', '--configuration', 'Release']

  - id: 'test'
    name: 'mcr.microsoft.com/dotnet/sdk:6.0.102-focal'
    entrypoint: 'dotnet'
    args: ['test']